language: objective-c
osx_image: xcode7.1

script: 
- xctool -project Objective-C/DDCollectionViewFlowLayout.xcodeproj -scheme DDCollectionViewFlowLayout -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' ONLY_ACTIVE_ARCH=NO
- xctool -project Swift/DDCollectionViewFlowLayout_Swift.xcodeproj -scheme DDCollectionViewFlowLayout_Swift -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' ONLY_ACTIVE_ARCH=NO; 
